2023-09-08 07:46:03 [scrapy] DEBUG: Redirecting (302) to <GET https://www.google.com/sorry/index?continue=https://www.google.com/search%3Fq%3Diphone%2B14%26hl%3Den%26gl%3DDK%26start%3D0&hl=en&q=EgRdpA0SGOuV6qcGIjBm-INXsw3Kb-7P7xok1il2pXgf7fT9S_JMXnxEV0w66biXzEMDm0CxEy5GpYuVPJ0yAXJaAUM> from <GET https://www.google.com/search?q=iphone+14&hl=en&gl=DK&start=0>
2023-09-08 07:46:03 [scrapy] DEBUG: Redirecting (302) to <GET https://www.google.com/sorry/index?continue=https://www.google.com/search%3Fq%3D%2Bapple%26hl%3Den%26gl%3DDK%26start%3D0&hl=en&q=EgRdpA0SGOuV6qcGIjCS0Q1hbZ-xkphfENqiQZRM6kJJHKUws4TTyTeQcOnTwQpxXoWG6XzsTP26qdx8aiEyAXJaAUM> from <GET https://www.google.com/search?q=+apple&hl=en&gl=DK&start=0>
2023-09-08 07:46:03 [scrapy] DEBUG: Retrying <GET https://www.google.com/sorry/index?continue=https://www.google.com/search%3Fq%3D%2Bapple%26hl%3Den%26gl%3DDK%26start%3D0&hl=en&q=EgRdpA0SGOuV6qcGIjCS0Q1hbZ-xkphfENqiQZRM6kJJHKUws4TTyTeQcOnTwQpxXoWG6XzsTP26qdx8aiEyAXJaAUM> (failed 1 times): 429 Unknown Status
2023-09-08 07:46:03 [scrapy] DEBUG: Retrying <GET https://www.google.com/sorry/index?continue=https://www.google.com/search%3Fq%3Diphone%2B14%26hl%3Den%26gl%3DDK%26start%3D0&hl=en&q=EgRdpA0SGOuV6qcGIjBm-INXsw3Kb-7P7xok1il2pXgf7fT9S_JMXnxEV0w66biXzEMDm0CxEy5GpYuVPJ0yAXJaAUM> (failed 1 times): 429 Unknown Status
2023-09-08 07:46:03 [scrapy] DEBUG: Crawled (200) <GET https://www.google.com/search?q=+ps5&hl=en&gl=DK&start=0> (referer: None)
2023-09-08 07:46:03 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' ps5',
 'position': 1,
 'price': '3.690,00\xa0kr.',
 'product_url': 'https://www.proshop.dk/Spillekonsol/Sony-5-Digital-Edition-Nordic/3033825?utm_source=google&utm_medium=cpc&utm_campaign=searchengine',
 'title': 'Sony 5 - Digital Edition (Nordic)',
 'url': 'proshop.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_code=item['country'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 653, in get
    raise self.model.MultipleObjectsReturned(
search.models.Location.MultipleObjectsReturned: get() returned more than one Location -- it returned 2!
2023-09-08 07:46:03 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' ps5',
 'position': 2,
 'price': '3.879,00\xa0kr.',
 'product_url': 'https://www.elgiganten.dk/product/gaming/spillekonsol-tilbehor/playstation/playstation-spillekonsol/playstation-5-digital-edition-2022/533977',
 'title': 'PlayStation 5 Digital Edition (2022)',
 'url': 'elgiganten.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_code=item['country'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 653, in get
    raise self.model.MultipleObjectsReturned(
search.models.Location.MultipleObjectsReturned: get() returned more than one Location -- it returned 2!
2023-09-08 07:46:03 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' ps5',
 'position': 3,
 'price': '2.999,00\xa0kr.',
 'product_url': 'https://www.telia.dk/shop/playstation/sony-playstation-5-23-bundle-med-abonnement/#/white/0-gb',
 'title': 'Sony PlayStation 5 med abonnement. Min.pris: 5.302,00kr. 6 mdr. '
          'binding',
 'url': 'telia.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_code=item['country'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 653, in get
    raise self.model.MultipleObjectsReturned(
search.models.Location.MultipleObjectsReturned: get() returned more than one Location -- it returned 2!
2023-09-08 07:46:03 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' ps5',
 'position': 4,
 'price': '3.777,00\xa0kr.',
 'product_url': 'https://www.power.dk/gaming-og-underholdning/playstation/playstation-konsoller/playstation-5-digital-edition/p-1840112/',
 'title': 'PLAYSTATION 5 DIGITAL EDITION',
 'url': 'power.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_code=item['country'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 653, in get
    raise self.model.MultipleObjectsReturned(
search.models.Location.MultipleObjectsReturned: get() returned more than one Location -- it returned 2!
2023-09-08 07:46:03 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' ps5',
 'position': 5,
 'price': '3.999,00\xa0kr.',
 'product_url': 'https://www.foetex.dk/produkter/ps5-digital-inkl-god-of-war/200169973/',
 'title': '"PS5 Digital inkl. God of War"',
 'url': 'foetex.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_code=item['country'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 653, in get
    raise self.model.MultipleObjectsReturned(
search.models.Location.MultipleObjectsReturned: get() returned more than one Location -- it returned 2!
2023-09-08 07:46:03 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' ps5',
 'position': 6,
 'price': '3.792,00\xa0kr.',
 'product_url': 'https://www.elgiganten.dk/product/outlet/playstation-5-2022/555353',
 'title': 'PlayStation 5 (2022)',
 'url': 'elgiganten.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_code=item['country'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 653, in get
    raise self.model.MultipleObjectsReturned(
search.models.Location.MultipleObjectsReturned: get() returned more than one Location -- it returned 2!
2023-09-08 07:46:03 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' ps5',
 'position': 7,
 'price': '4.491,00\xa0kr.',
 'product_url': 'https://www.elgiganten.dk/product/outlet/playstation-5-2x-dualsense-controller-pakke/592211',
 'title': 'PlayStation 5 + 2x DualSense controller-pakke',
 'url': 'elgiganten.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_code=item['country'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 653, in get
    raise self.model.MultipleObjectsReturned(
search.models.Location.MultipleObjectsReturned: get() returned more than one Location -- it returned 2!
2023-09-08 07:46:03 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' ps5',
 'position': 8,
 'price': '4.359,00\xa0kr.',
 'product_url': 'https://www.power.dk/gaming-og-underholdning/playstation/playstation-konsoller/playstation-5/p-1840111/',
 'title': 'PLAYSTATION 5',
 'url': 'power.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_code=item['country'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 653, in get
    raise self.model.MultipleObjectsReturned(
search.models.Location.MultipleObjectsReturned: get() returned more than one Location -- it returned 2!
2023-09-08 07:46:03 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' ps5',
 'position': 9,
 'price': '4.799,00\xa0kr.',
 'product_url': 'https://www.foetex.dk/produkter/ps5-standard-konsol-inkl-2-x-hvid-dualsense/200183008/',
 'title': '"PS5 Standard Konsol inkl. 2 x hvid Dualsense"',
 'url': 'foetex.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_code=item['country'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 653, in get
    raise self.model.MultipleObjectsReturned(
search.models.Location.MultipleObjectsReturned: get() returned more than one Location -- it returned 2!
2023-09-08 07:46:03 [scrapy] DEBUG: Crawled (200) <GET https://www.google.com/search?q=+macbook&hl=en&gl=DK&start=0> (referer: None)
2023-09-08 07:46:04 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' macbook',
 'position': 1,
 'price': '28.899,00\xa0kr.',
 'product_url': 'https://www.humac.dk/produkter/mac/macbook-pro-2023-m2-pro-162-12cpu19gpu1tb-sg-premium-konfigureret-ud-fra-mnw93dka',
 'title': 'MacBook Pro 2023 M2 Pro 16.2" 12CPU/19GPU/1TB SG',
 'url': 'humac.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_code=item['country'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 653, in get
    raise self.model.MultipleObjectsReturned(
search.models.Location.MultipleObjectsReturned: get() returned more than one Location -- it returned 2!
2023-09-08 07:46:04 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' macbook',
 'position': 2,
 'price': '6.084,99\xa0kr.',
 'product_url': 'https://www.refurbed.dk/p/macbook-pro-2019-133-tb/?co=dk&utm_cluster=gradeC&utm_content=macbook-pro-2019-133-tb&utm_group=macbook-pro-2019-133-tb',
 'title': 'Apple MacBook Pro 2019 | 13.3" | Touch Bar',
 'url': 'refurbed.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_code=item['country'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 653, in get
    raise self.model.MultipleObjectsReturned(
search.models.Location.MultipleObjectsReturned: get() returned more than one Location -- it returned 2!
2023-09-08 07:46:04 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' macbook',
 'position': 3,
 'price': '7.649,00\xa0kr.',
 'product_url': 'https://www.elgiganten.dk/product/computer-kontor/computere/barbar-computer/macbook-air-13-m18256-2020-space-grey/254420',
 'title': 'MacBook Air 13 M1/8/256 2020 (space grey)',
 'url': 'elgiganten.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_code=item['country'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 653, in get
    raise self.model.MultipleObjectsReturned(
search.models.Location.MultipleObjectsReturned: get() returned more than one Location -- it returned 2!
2023-09-08 07:46:04 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' macbook',
 'position': 4,
 'price': '28.899,00\xa0kr.',
 'product_url': 'https://www.humac.dk/produkter/mac/macbook-pro-2023-m2-max-142-12cpu30gpu1tb-sg',
 'title': 'MacBook Pro 2023 M2 Max 14.2" 12CPU/30GPU/1TB SG',
 'url': 'humac.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_code=item['country'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 653, in get
    raise self.model.MultipleObjectsReturned(
search.models.Location.MultipleObjectsReturned: get() returned more than one Location -- it returned 2!
2023-09-08 07:46:04 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' macbook',
 'position': 5,
 'price': '4.768,99\xa0kr.',
 'product_url': 'https://www.refurbed.dk/p/apple-macbook-pro-2018-13-3-touc/?co=dk&utm_cluster=gradeC&utm_content=apple-macbook-pro-2018-13-3-touc&utm_group=apple-macbook-pro-2018-13-3-touc',
 'title': 'Apple MacBook Pro 2018 | 13.3" | Touch Bar',
 'url': 'refurbed.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_code=item['country'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 653, in get
    raise self.model.MultipleObjectsReturned(
search.models.Location.MultipleObjectsReturned: get() returned more than one Location -- it returned 2!
2023-09-08 07:46:04 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' macbook',
 'position': 6,
 'price': '7.649,00\xa0kr.',
 'product_url': 'https://www.power.dk/computere-og-tablets/computere/baerbar-pc/apple-macbook-air-2020-m1-mgn63dka-13-256-gb-space-grey/p-1133484/',
 'title': 'APPLE MACBOOK AIR 2020 M1 MGN63DK/A 13" 256 GB SPACE GREY',
 'url': 'power.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_code=item['country'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 653, in get
    raise self.model.MultipleObjectsReturned(
search.models.Location.MultipleObjectsReturned: get() returned more than one Location -- it returned 2!
2023-09-08 07:46:04 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' macbook',
 'position': 7,
 'price': '7.649,00\xa0kr.',
 'product_url': 'https://www.bilka.dk/produkter/apple-macbook-air-m1-13-256-gb-space-grey/100558134/',
 'title': 'Apple Macbook Air M1 13" 256 GB Space Grey',
 'url': 'bilka.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_code=item['country'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 653, in get
    raise self.model.MultipleObjectsReturned(
search.models.Location.MultipleObjectsReturned: get() returned more than one Location -- it returned 2!
2023-09-08 07:46:04 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' macbook',
 'position': 8,
 'price': '4.425,99\xa0kr.',
 'product_url': 'https://www.refurbed.dk/p/apple-macbook-pro-2017-13-3-touc/?co=dk&utm_cluster=gradeB&utm_content=apple-macbook-pro-2017-13-3-touc&utm_group=apple-macbook-pro-2017-13-3-touc',
 'title': 'Apple MacBook Pro 2017 | 13.3" | Touch Bar',
 'url': 'refurbed.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_code=item['country'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 653, in get
    raise self.model.MultipleObjectsReturned(
search.models.Location.MultipleObjectsReturned: get() returned more than one Location -- it returned 2!
2023-09-08 07:46:04 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' macbook',
 'position': 9,
 'price': '12.499,00\xa0kr.',
 'product_url': 'https://www.humac.dk/produkter/mac/macbook-air-2023-m2-15-8cpu-10gpu-256gb-sg',
 'title': 'MacBook Air 2023 M2 15" 8CPU 10GPU 256GB SG',
 'url': 'humac.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_code=item['country'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 653, in get
    raise self.model.MultipleObjectsReturned(
search.models.Location.MultipleObjectsReturned: get() returned more than one Location -- it returned 2!
2023-09-08 07:46:04 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' macbook',
 'position': 10,
 'price': '2.800,99\xa0kr.',
 'product_url': 'https://www.refurbed.dk/p/apple-macbook-pro-2015-13-3/?co=dk&utm_cluster=gradeC&utm_content=apple-macbook-pro-2015-13-3&utm_group=apple-macbook-pro-2015-13-3',
 'title': 'Apple MacBook Pro 2015 | 13.3"',
 'url': 'refurbed.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_code=item['country'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 653, in get
    raise self.model.MultipleObjectsReturned(
search.models.Location.MultipleObjectsReturned: get() returned more than one Location -- it returned 2!
2023-09-08 07:46:04 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' macbook',
 'position': 11,
 'price': '7.649,00\xa0kr.',
 'product_url': 'https://www.foetex.dk/produkter/apple-macbook-air-m1-13-256-gb-guld/100558142/',
 'title': '"Apple Macbook Air M1 13 256 GB Guld"',
 'url': 'foetex.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_code=item['country'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 653, in get
    raise self.model.MultipleObjectsReturned(
search.models.Location.MultipleObjectsReturned: get() returned more than one Location -- it returned 2!
2023-09-08 07:46:04 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' macbook',
 'position': 12,
 'price': '23.499,00\xa0kr.',
 'product_url': 'https://www.humac.dk/produkter/mac/macbook-pro-2023-m2-pro-142-12cpu19gpu1tb-si',
 'title': 'MacBook Pro 2023 M2 Pro 14.2" 12CPU/19GPU/1TB SI',
 'url': 'humac.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_code=item['country'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 653, in get
    raise self.model.MultipleObjectsReturned(
search.models.Location.MultipleObjectsReturned: get() returned more than one Location -- it returned 2!
2023-09-08 07:46:04 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' macbook',
 'position': 13,
 'price': '3.246,99\xa0kr.',
 'product_url': 'https://www.refurbed.dk/p/apple-macbook-air-2017-i-13-3/?co=dk&utm_cluster=gradeC&utm_content=apple-macbook-air-2017-i-13-3&utm_group=apple-macbook-air-2017-i-13-3',
 'title': 'Apple MacBook Air 2017 | 13.3"',
 'url': 'refurbed.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_code=item['country'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 653, in get
    raise self.model.MultipleObjectsReturned(
search.models.Location.MultipleObjectsReturned: get() returned more than one Location -- it returned 2!
2023-09-08 07:46:04 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' macbook',
 'position': 14,
 'price': '13.199,00\xa0kr.',
 'product_url': 'https://www.humac.dk/produkter/mac/macbook-air-2022-m2-136-10c-cpu-8gb-512gb-mdn',
 'title': 'MacBook Air 2022 M2 13.6" 10C GPU, 8GB, 512GB MDN',
 'url': 'humac.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_code=item['country'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 653, in get
    raise self.model.MultipleObjectsReturned(
search.models.Location.MultipleObjectsReturned: get() returned more than one Location -- it returned 2!
2023-09-08 07:46:04 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' macbook',
 'position': 15,
 'price': '7.649,00\xa0kr.',
 'product_url': 'https://www.power.dk/computere-og-tablets/computere/baerbar-pc/apple-macbook-air-2020-m1-mgnd3dka-13-256-gb-guld/p-1133485/',
 'title': 'APPLE MACBOOK AIR 2020 M1 MGND3DK/A 13" 256 GB GULD',
 'url': 'power.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_code=item['country'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 653, in get
    raise self.model.MultipleObjectsReturned(
search.models.Location.MultipleObjectsReturned: get() returned more than one Location -- it returned 2!
2023-09-08 07:46:04 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' macbook',
 'position': 16,
 'price': '12.499,00\xa0kr.',
 'product_url': 'https://www.humac.dk/produkter/mac/macbook-air-2023-m2-15-8cpu-10gpu-256gb-stl',
 'title': 'MacBook Air 2023 M2 15" 8CPU 10GPU 256GB STL',
 'url': 'humac.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_code=item['country'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 653, in get
    raise self.model.MultipleObjectsReturned(
search.models.Location.MultipleObjectsReturned: get() returned more than one Location -- it returned 2!
2023-09-08 07:46:04 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' macbook',
 'position': 17,
 'price': '7.071,99\xa0kr.',
 'product_url': 'https://www.refurbed.dk/p/apple-macbook-pro-2020-133-tb/?co=dk&utm_cluster=gradeC&utm_content=apple-macbook-pro-2020-133-tb&utm_group=apple-macbook-pro-2020-133-tb',
 'title': 'Apple MacBook Pro 2020 | 13.3" | Touch Bar',
 'url': 'refurbed.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_code=item['country'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 653, in get
    raise self.model.MultipleObjectsReturned(
search.models.Location.MultipleObjectsReturned: get() returned more than one Location -- it returned 2!
2023-09-08 07:46:04 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' macbook',
 'position': 18,
 'price': '63.991,30\xa0kr.',
 'product_url': 'https://www.elfadistrelec.dk/da/notebook-macbook-pro-2021-16-41-cm-apple-m1-max-06ghz-8tb-ssd-64gb-ddr4-gra-apple-z14x-gr08/p/30261466',
 'title': 'Apple Notebook, MacBook Pro 2021, 16.2" (41.1 cm), Apple M1 Max, '
          '2.06GHz, 8TB SSD, 64GB DDR4, Grå - Z14X-GR08',
 'url': 'elfadistrelec.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_code=item['country'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 653, in get
    raise self.model.MultipleObjectsReturned(
search.models.Location.MultipleObjectsReturned: get() returned more than one Location -- it returned 2!
2023-09-08 07:46:04 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' macbook',
 'position': 19,
 'price': '10.049,00\xa0kr.',
 'product_url': 'https://www.elgiganten.dk/product/computer-kontor/computere/barbar-computer/macbook-air-m2-2022-8256-gb-barbar-computer-midnight/474934',
 'title': 'MacBook Air M2 2022 8/256 GB bærbar computer (Midnight)',
 'url': 'elgiganten.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_code=item['country'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 653, in get
    raise self.model.MultipleObjectsReturned(
search.models.Location.MultipleObjectsReturned: get() returned more than one Location -- it returned 2!
2023-09-08 07:46:04 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' macbook',
 'position': 20,
 'price': '10.059,00\xa0kr.',
 'product_url': 'https://greenmind.dk/computere/baerbar/apple-macbooks/macbook-pro/apple-macbook-pro-16-0-2-6-ghz-512-gb-ssd-16-gb-2019-gra-us-brugt-som-ny-62132',
 'title': 'Apple MacBook Pro 16.0" 2.6 GHz 16 GB 512 GB [SSD] 2019 Grå US '
          'Brugt - Som ny',
 'url': 'greenmind.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_code=item['country'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 653, in get
    raise self.model.MultipleObjectsReturned(
search.models.Location.MultipleObjectsReturned: get() returned more than one Location -- it returned 2!
2023-09-08 07:46:04 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' macbook',
 'position': 21,
 'price': '7.649,00\xa0kr.',
 'product_url': 'https://www.bilka.dk/produkter/apple-macbook-air-m1-13-256-gb-guld/100558142/',
 'title': 'Apple Macbook Air M1 13" 256 GB Guld',
 'url': 'bilka.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_code=item['country'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 653, in get
    raise self.model.MultipleObjectsReturned(
search.models.Location.MultipleObjectsReturned: get() returned more than one Location -- it returned 2!
2023-09-08 07:46:04 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' macbook',
 'position': 22,
 'price': '7.649,00\xa0kr.',
 'product_url': 'https://www.foetex.dk/produkter/apple-macbook-air-m1-13-256-gb-silver/100558137/',
 'title': '"Apple Macbook Air M1 13 256 GB Silver"',
 'url': 'foetex.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_code=item['country'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 653, in get
    raise self.model.MultipleObjectsReturned(
search.models.Location.MultipleObjectsReturned: get() returned more than one Location -- it returned 2!
2023-09-08 07:46:04 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' macbook',
 'position': 23,
 'price': '13.199,00\xa0kr.',
 'product_url': 'https://www.humac.dk/produkter/mac/macbook-air-2022-m2-136-10c-cpu-8gb-512gb-stl',
 'title': 'MacBook Air 2022 M2 13.6" 10C GPU, 8GB, 512GB STL',
 'url': 'humac.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_code=item['country'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 653, in get
    raise self.model.MultipleObjectsReturned(
search.models.Location.MultipleObjectsReturned: get() returned more than one Location -- it returned 2!
2023-09-08 07:46:04 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' macbook',
 'position': 24,
 'price': '4.003,99\xa0kr.',
 'product_url': 'https://www.refurbed.dk/p/apple-macbook-pro-2017-i5-13/13237c/?co=dk&utm_cluster=gradeC&utm_content=apple-macbook-pro-2017-i5-13-13237c&utm_group=apple-macbook-pro-2017-i5-13',
 'title': 'Apple MacBook Pro 2017 | 13.3" | 2.3 GHz | 8 GB | 128 GB SSD | '
          'spacegrey | US',
 'url': 'refurbed.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_code=item['country'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 653, in get
    raise self.model.MultipleObjectsReturned(
search.models.Location.MultipleObjectsReturned: get() returned more than one Location -- it returned 2!
2023-09-08 07:46:04 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' macbook',
 'position': 25,
 'price': '5.781,99\xa0kr.',
 'product_url': 'https://www.refurbed.dk/p/apple-macbook-air-2020/?co=dk&utm_cluster=gradeC&utm_content=apple-macbook-air-2020&utm_group=apple-macbook-air-2020',
 'title': '>> Apple MacBook Air 2020 | 13.3" <<',
 'url': 'refurbed.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_code=item['country'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 653, in get
    raise self.model.MultipleObjectsReturned(
search.models.Location.MultipleObjectsReturned: get() returned more than one Location -- it returned 2!
2023-09-08 07:46:04 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' macbook',
 'position': 26,
 'price': '11.299,00\xa0kr.',
 'product_url': 'https://www.bilka.dk/produkter/apple-macbook-pro-m2-13-3-256-gb-silver/200153771/',
 'title': 'Apple Macbook Pro M2 13,3" 256 GB Silver',
 'url': 'bilka.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_code=item['country'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 653, in get
    raise self.model.MultipleObjectsReturned(
search.models.Location.MultipleObjectsReturned: get() returned more than one Location -- it returned 2!
2023-09-08 07:46:04 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' macbook',
 'position': 27,
 'price': '7.649,00\xa0kr.',
 'product_url': 'https://www.power.dk/computere-og-tablets/computere/baerbar-pc/apple-macbook-air-2020-m1-mgn93dka-13-256-gb-soelv/p-1133486/',
 'title': 'APPLE MACBOOK AIR 2020 M1 MGN93DK/A 13" 256 GB SØLV',
 'url': 'power.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_code=item['country'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 653, in get
    raise self.model.MultipleObjectsReturned(
search.models.Location.MultipleObjectsReturned: get() returned more than one Location -- it returned 2!
2023-09-08 07:46:04 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' macbook',
 'position': 28,
 'price': '10.499,00\xa0kr.',
 'product_url': 'https://www.humac.dk/produkter/mac/macbook-air-2022-m2-136-8c-cpu-8gb-256gb-sl',
 'title': 'MacBook Air 2022 M2 13.6" 8C GPU, 8GB, 256GB SIL',
 'url': 'humac.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_code=item['country'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 653, in get
    raise self.model.MultipleObjectsReturned(
search.models.Location.MultipleObjectsReturned: get() returned more than one Location -- it returned 2!
2023-09-08 07:46:04 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' macbook',
 'position': 29,
 'price': '2.300,99\xa0kr.',
 'product_url': 'https://www.refurbed.dk/p/apple-macbook-air-2015-13-3/?co=dk&utm_cluster=gradeC&utm_content=apple-macbook-air-2015-13-3&utm_group=apple-macbook-air-2015-13-3',
 'title': 'Apple MacBook Air 2015 | 13.3"',
 'url': 'refurbed.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_code=item['country'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 653, in get
    raise self.model.MultipleObjectsReturned(
search.models.Location.MultipleObjectsReturned: get() returned more than one Location -- it returned 2!
2023-09-08 07:46:04 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' macbook',
 'position': 30,
 'price': None,
 'product_url': None,
 'title': None,
 'url': '',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_code=item['country'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 653, in get
    raise self.model.MultipleObjectsReturned(
search.models.Location.MultipleObjectsReturned: get() returned more than one Location -- it returned 2!
2023-09-08 07:46:04 [scrapy] DEBUG: Retrying <GET https://www.google.com/sorry/index?continue=https://www.google.com/search%3Fq%3D%2Bapple%26hl%3Den%26gl%3DDK%26start%3D0&hl=en&q=EgRdpA0SGOuV6qcGIjCS0Q1hbZ-xkphfENqiQZRM6kJJHKUws4TTyTeQcOnTwQpxXoWG6XzsTP26qdx8aiEyAXJaAUM> (failed 2 times): 429 Unknown Status
2023-09-08 07:46:04 [scrapy] DEBUG: Retrying <GET https://www.google.com/sorry/index?continue=https://www.google.com/search%3Fq%3Diphone%2B14%26hl%3Den%26gl%3DDK%26start%3D0&hl=en&q=EgRdpA0SGOuV6qcGIjBm-INXsw3Kb-7P7xok1il2pXgf7fT9S_JMXnxEV0w66biXzEMDm0CxEy5GpYuVPJ0yAXJaAUM> (failed 2 times): 429 Unknown Status
2023-09-08 07:46:04 [scrapy] DEBUG: Crawled (200) <GET https://www.google.com/search?q=+iphone+13&hl=en&gl=DK&start=0> (referer: None)
2023-09-08 07:46:04 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' iphone 13',
 'position': 1,
 'price': '5.666,00\xa0kr.',
 'product_url': 'https://www.elgiganten.dk/product/mobil-tablet-smartwatch/mobiltelefon/iphone-13-5g-smartphone-128gb-midnight/361879',
 'title': 'iPhone 13 – 5G smartphone 128GB Midnight',
 'url': 'elgiganten.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_code=item['country'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 653, in get
    raise self.model.MultipleObjectsReturned(
search.models.Location.MultipleObjectsReturned: get() returned more than one Location -- it returned 2!
2023-09-08 07:46:04 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' iphone 13',
 'position': 2,
 'price': '4.306,99\xa0kr.',
 'product_url': 'https://www.refurbed.dk/p/iphone-13/?co=dk&utm_cluster=gradeC&utm_content=iphone-13&utm_group=iphone-13',
 'title': 'iPhone 13',
 'url': 'refurbed.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_code=item['country'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 653, in get
    raise self.model.MultipleObjectsReturned(
search.models.Location.MultipleObjectsReturned: get() returned more than one Location -- it returned 2!
2023-09-08 07:46:04 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' iphone 13',
 'position': 3,
 'price': '4.799,00\xa0kr.',
 'product_url': 'https://www.telenor.dk/shop/mobil/apple/apple-iphone-13--128gb-midnight/?cycleCount=none',
 'title': 'Apple iPhone 13 - 128 GB - Midnight med abonnementsaftale. '
          'Mindstepris 6613.00 Kr.',
 'url': 'telenor.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_code=item['country'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 653, in get
    raise self.model.MultipleObjectsReturned(
search.models.Location.MultipleObjectsReturned: get() returned more than one Location -- it returned 2!
2023-09-08 07:46:04 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' iphone 13',
 'position': 4,
 'price': '5.666,00\xa0kr.',
 'product_url': 'https://www.power.dk/mobil-og-foto/mobiltelefoner/apple-iphone-13-128-gb-midnat/p-1204127/',
 'title': 'APPLE IPHONE 13 128 GB MIDNAT',
 'url': 'power.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_code=item['country'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 653, in get
    raise self.model.MultipleObjectsReturned(
search.models.Location.MultipleObjectsReturned: get() returned more than one Location -- it returned 2!
2023-09-08 07:46:04 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' iphone 13',
 'position': 5,
 'price': '4.899,00\xa0kr.',
 'product_url': 'https://www.telia.dk/shop/apple/apple-iphone-13/#/pink/128-gb/1',
 'title': 'Apple iPhone 13 128GB Pink. Min.pris: 6.702,00kr. 6 mdr. binding',
 'url': 'telia.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_code=item['country'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 653, in get
    raise self.model.MultipleObjectsReturned(
search.models.Location.MultipleObjectsReturned: get() returned more than one Location -- it returned 2!
2023-09-08 07:46:04 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' iphone 13',
 'position': 6,
 'price': '4.759,00\xa0kr.',
 'product_url': 'https://swappie.com/dk/iphone/iphone-13/iphone-13-128gb-bla-4/',
 'title': 'iPhone 13 128GB Blå Apple',
 'url': 'swappie.com',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_code=item['country'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 653, in get
    raise self.model.MultipleObjectsReturned(
search.models.Location.MultipleObjectsReturned: get() returned more than one Location -- it returned 2!
2023-09-08 07:46:04 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' iphone 13',
 'position': 7,
 'price': '4.306,99\xa0kr.',
 'product_url': 'https://www.refurbed.dk/p/iphone-13/14156c/?co=dk&utm_cluster=gradeC&utm_content=iphone-13-14156c&utm_group=iphone-13',
 'title': 'iPhone 13 | 128 GB | Dual-SIM | pink',
 'url': 'refurbed.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_code=item['country'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 653, in get
    raise self.model.MultipleObjectsReturned(
search.models.Location.MultipleObjectsReturned: get() returned more than one Location -- it returned 2!
2023-09-08 07:46:04 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' iphone 13',
 'position': 8,
 'price': '4.799,00\xa0kr.',
 'product_url': 'https://www.telenor.dk/shop/mobil/apple/iphone-13-128gb-green/?cycleCount=none',
 'title': 'Apple iPhone 13 - 128 GB - Grøn med abonnementsaftale. Mindstepris '
          '6613.00 Kr.',
 'url': 'telenor.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_code=item['country'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 653, in get
    raise self.model.MultipleObjectsReturned(
search.models.Location.MultipleObjectsReturned: get() returned more than one Location -- it returned 2!
2023-09-08 07:46:04 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' iphone 13',
 'position': 9,
 'price': '5.666,00\xa0kr.',
 'product_url': 'https://www.elgiganten.dk/product/mobil-tablet-smartwatch/mobiltelefon/iphone-13-5g-smartphone-128gb-starlight/361914',
 'title': 'iPhone 13 – 5G smartphone 128GB Starlight',
 'url': 'elgiganten.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_code=item['country'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 653, in get
    raise self.model.MultipleObjectsReturned(
search.models.Location.MultipleObjectsReturned: get() returned more than one Location -- it returned 2!
2023-09-08 07:46:04 [scrapy] ERROR: Gave up retrying <GET https://www.google.com/sorry/index?continue=https://www.google.com/search%3Fq%3D%2Bapple%26hl%3Den%26gl%3DDK%26start%3D0&hl=en&q=EgRdpA0SGOuV6qcGIjCS0Q1hbZ-xkphfENqiQZRM6kJJHKUws4TTyTeQcOnTwQpxXoWG6XzsTP26qdx8aiEyAXJaAUM> (failed 3 times): 429 Unknown Status
2023-09-08 07:46:04 [scrapy] DEBUG: Crawled (429) <GET https://www.google.com/sorry/index?continue=https://www.google.com/search%3Fq%3D%2Bapple%26hl%3Den%26gl%3DDK%26start%3D0&hl=en&q=EgRdpA0SGOuV6qcGIjCS0Q1hbZ-xkphfENqiQZRM6kJJHKUws4TTyTeQcOnTwQpxXoWG6XzsTP26qdx8aiEyAXJaAUM> (referer: None)
2023-09-08 07:46:04 [scrapy] INFO: Ignoring response <429 https://www.google.com/sorry/index?continue=https://www.google.com/search%3Fq%3D%2Bapple%26hl%3Den%26gl%3DDK%26start%3D0&hl=en&q=EgRdpA0SGOuV6qcGIjCS0Q1hbZ-xkphfENqiQZRM6kJJHKUws4TTyTeQcOnTwQpxXoWG6XzsTP26qdx8aiEyAXJaAUM>: HTTP status code is not handled or not allowed
2023-09-08 07:46:04 [scrapy] ERROR: Gave up retrying <GET https://www.google.com/sorry/index?continue=https://www.google.com/search%3Fq%3Diphone%2B14%26hl%3Den%26gl%3DDK%26start%3D0&hl=en&q=EgRdpA0SGOuV6qcGIjBm-INXsw3Kb-7P7xok1il2pXgf7fT9S_JMXnxEV0w66biXzEMDm0CxEy5GpYuVPJ0yAXJaAUM> (failed 3 times): 429 Unknown Status
2023-09-08 07:46:04 [scrapy] DEBUG: Crawled (429) <GET https://www.google.com/sorry/index?continue=https://www.google.com/search%3Fq%3Diphone%2B14%26hl%3Den%26gl%3DDK%26start%3D0&hl=en&q=EgRdpA0SGOuV6qcGIjBm-INXsw3Kb-7P7xok1il2pXgf7fT9S_JMXnxEV0w66biXzEMDm0CxEy5GpYuVPJ0yAXJaAUM> (referer: None)
2023-09-08 07:46:04 [scrapy] INFO: Ignoring response <429 https://www.google.com/sorry/index?continue=https://www.google.com/search%3Fq%3Diphone%2B14%26hl%3Den%26gl%3DDK%26start%3D0&hl=en&q=EgRdpA0SGOuV6qcGIjBm-INXsw3Kb-7P7xok1il2pXgf7fT9S_JMXnxEV0w66biXzEMDm0CxEy5GpYuVPJ0yAXJaAUM>: HTTP status code is not handled or not allowed
2023-09-08 07:46:04 [scrapy] INFO: Closing spider (finished)
2023-09-08 07:46:04 [scrapy] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 7319,
 'downloader/request_count': 11,
 'downloader/request_method_count/GET': 11,
 'downloader/response_bytes': 707918,
 'downloader/response_count': 11,
 'downloader/response_status_count/200': 3,
 'downloader/response_status_count/302': 2,
 'downloader/response_status_count/429': 6,
 'elapsed_time_seconds': 4.55433,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2023, 9, 8, 2, 46, 4, 924679),
 'httpcompression/response_bytes': 2571181,
 'httpcompression/response_count': 3,
 'httperror/response_ignored_count': 2,
 'httperror/response_ignored_status_count/429': 2,
 'log_count/DEBUG': 11,
 'log_count/ERROR': 50,
 'log_count/INFO': 10,
 'response_received_count': 5,
 'retry/count': 4,
 'retry/max_reached': 2,
 'retry/reason_count/429 Unknown Status': 4,
 'scheduler/dequeued': 11,
 'scheduler/dequeued/memory': 11,
 'scheduler/enqueued': 11,
 'scheduler/enqueued/memory': 11,
 'start_time': datetime.datetime(2023, 9, 8, 2, 46, 0, 370349)}
2023-09-08 07:46:04 [scrapy] INFO: Spider closed (finished)
