2023-09-08 07:40:15 [scrapy] DEBUG: Redirecting (302) to <GET https://www.google.com/sorry/index?continue=https://www.google.com/search%3Fq%3D%2Biphone%2B13%26hl%3Den%26gl%3DDK%26start%3D0&hl=en&q=EgRdpA0SGJCT6qcGIjBXI7u1WVTgoFs4V8RlvhS3FUlVLZlKQsxYr-8YrJNl3mVtbnXJlw7m1pj95GgLibIyAXJaAUM> from <GET https://www.google.com/search?q=+iphone+13&hl=en&gl=DK&start=0>
2023-09-08 07:40:16 [scrapy] DEBUG: Crawled (200) <GET https://www.google.com/search?q=+apple&hl=en&gl=DK&start=0> (referer: None)
2023-09-08 07:40:16 [scrapy] DEBUG: Retrying <GET https://www.google.com/sorry/index?continue=https://www.google.com/search%3Fq%3D%2Biphone%2B13%26hl%3Den%26gl%3DDK%26start%3D0&hl=en&q=EgRdpA0SGJCT6qcGIjBXI7u1WVTgoFs4V8RlvhS3FUlVLZlKQsxYr-8YrJNl3mVtbnXJlw7m1pj95GgLibIyAXJaAUM> (failed 1 times): 429 Unknown Status
2023-09-08 07:40:16 [scrapy] DEBUG: Crawled (200) <GET https://www.google.com/search?q=+macbook&hl=en&gl=DK&start=0> (referer: None)
2023-09-08 07:40:16 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' macbook',
 'position': 1,
 'price': '12.499,00\xa0kr.',
 'product_url': 'https://www.humac.dk/produkter/mac/macbook-air-2023-m2-15-8cpu-10gpu-256gb-mdn',
 'title': 'MacBook Air 2023 M2 15" 8CPU 10GPU 256GB MDN',
 'url': 'humac.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_name=item['country_name'])
                                                 ~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\scrapy\item.py", line 79, in __getitem__
    return self._values[key]
           ~~~~~~~~~~~~^^^^^
KeyError: 'country_name'
2023-09-08 07:40:16 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' macbook',
 'position': 2,
 'price': '6.084,99\xa0kr.',
 'product_url': 'https://www.refurbed.dk/p/macbook-pro-2019-133-tb/?co=dk&utm_cluster=gradeC&utm_content=macbook-pro-2019-133-tb&utm_group=macbook-pro-2019-133-tb',
 'title': 'Apple MacBook Pro 2019 | 13.3" | Touch Bar',
 'url': 'refurbed.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_name=item['country_name'])
                                                 ~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\scrapy\item.py", line 79, in __getitem__
    return self._values[key]
           ~~~~~~~~~~~~^^^^^
KeyError: 'country_name'
2023-09-08 07:40:16 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' macbook',
 'position': 3,
 'price': '32.499,00\xa0kr.',
 'product_url': 'https://www.humac.dk/produkter/mac/macbook-pro-2023-m2-max-162-12cpu38gpu1tb-sg',
 'title': 'MacBook Pro 2023 M2 Max 16.2" 12CPU/38GPU/1TB SG',
 'url': 'humac.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_name=item['country_name'])
                                                 ~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\scrapy\item.py", line 79, in __getitem__
    return self._values[key]
           ~~~~~~~~~~~~^^^^^
KeyError: 'country_name'
2023-09-08 07:40:16 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' macbook',
 'position': 4,
 'price': '7.649,00\xa0kr.',
 'product_url': 'https://www.elgiganten.dk/product/computer-kontor/computere/barbar-computer/macbook-air-13-m18256-2020-space-grey/254420',
 'title': 'MacBook Air 13 M1/8/256 2020 (space grey)',
 'url': 'elgiganten.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_name=item['country_name'])
                                                 ~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\scrapy\item.py", line 79, in __getitem__
    return self._values[key]
           ~~~~~~~~~~~~^^^^^
KeyError: 'country_name'
2023-09-08 07:40:16 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' macbook',
 'position': 5,
 'price': '7.649,00\xa0kr.',
 'product_url': 'https://www.bilka.dk/produkter/apple-macbook-air-m1-13-256-gb-space-grey/100558134/',
 'title': 'Apple Macbook Air M1 13" 256 GB Space Grey',
 'url': 'bilka.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_name=item['country_name'])
                                                 ~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\scrapy\item.py", line 79, in __getitem__
    return self._values[key]
           ~~~~~~~~~~~~^^^^^
KeyError: 'country_name'
2023-09-08 07:40:16 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' macbook',
 'position': 6,
 'price': '4.425,99\xa0kr.',
 'product_url': 'https://www.refurbed.dk/p/apple-macbook-pro-2017-13-3-touc/?co=dk&utm_cluster=gradeB&utm_content=apple-macbook-pro-2017-13-3-touc&utm_group=apple-macbook-pro-2017-13-3-touc',
 'title': 'Apple MacBook Pro 2017 | 13.3" | Touch Bar',
 'url': 'refurbed.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_name=item['country_name'])
                                                 ~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\scrapy\item.py", line 79, in __getitem__
    return self._values[key]
           ~~~~~~~~~~~~^^^^^
KeyError: 'country_name'
2023-09-08 07:40:16 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' macbook',
 'position': 7,
 'price': '28.899,00\xa0kr.',
 'product_url': 'https://www.humac.dk/produkter/mac/macbook-pro-2023-m2-max-142-12cpu30gpu1tb-sg',
 'title': 'MacBook Pro 2023 M2 Max 14.2" 12CPU/30GPU/1TB SG',
 'url': 'humac.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_name=item['country_name'])
                                                 ~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\scrapy\item.py", line 79, in __getitem__
    return self._values[key]
           ~~~~~~~~~~~~^^^^^
KeyError: 'country_name'
2023-09-08 07:40:16 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' macbook',
 'position': 8,
 'price': '7.649,00\xa0kr.',
 'product_url': 'https://www.power.dk/computere-og-tablets/computere/baerbar-pc/apple-macbook-air-2020-m1-mgn63dka-13-256-gb-space-grey/p-1133484/',
 'title': 'APPLE MACBOOK AIR 2020 M1 MGN63DK/A 13" 256 GB SPACE GREY',
 'url': 'power.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_name=item['country_name'])
                                                 ~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\scrapy\item.py", line 79, in __getitem__
    return self._values[key]
           ~~~~~~~~~~~~^^^^^
KeyError: 'country_name'
2023-09-08 07:40:16 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' macbook',
 'position': 9,
 'price': '4.768,99\xa0kr.',
 'product_url': 'https://www.refurbed.dk/p/apple-macbook-pro-2018-13-3-touc/?co=dk&utm_cluster=gradeC&utm_content=apple-macbook-pro-2018-13-3-touc&utm_group=apple-macbook-pro-2018-13-3-touc',
 'title': 'Apple MacBook Pro 2018 | 13.3" | Touch Bar',
 'url': 'refurbed.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_name=item['country_name'])
                                                 ~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\scrapy\item.py", line 79, in __getitem__
    return self._values[key]
           ~~~~~~~~~~~~^^^^^
KeyError: 'country_name'
2023-09-08 07:40:17 [scrapy] DEBUG: Crawled (200) <GET https://www.google.com/search?q=+ps5&hl=en&gl=DK&start=0> (referer: None)
2023-09-08 07:40:17 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' ps5',
 'position': 1,
 'price': '3.879,00\xa0kr.',
 'product_url': 'https://www.elgiganten.dk/product/gaming/spillekonsol-tilbehor/playstation/playstation-spillekonsol/playstation-5-digital-edition-2022/533977',
 'title': 'PlayStation 5 Digital Edition (2022)',
 'url': 'elgiganten.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_name=item['country_name'])
                                                 ~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\scrapy\item.py", line 79, in __getitem__
    return self._values[key]
           ~~~~~~~~~~~~^^^^^
KeyError: 'country_name'
2023-09-08 07:40:17 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' ps5',
 'position': 2,
 'price': '3.777,00\xa0kr.',
 'product_url': 'https://www.power.dk/gaming-og-underholdning/playstation/playstation-konsoller/playstation-5-digital-edition/p-1840112/',
 'title': 'PLAYSTATION 5 DIGITAL EDITION',
 'url': 'power.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_name=item['country_name'])
                                                 ~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\scrapy\item.py", line 79, in __getitem__
    return self._values[key]
           ~~~~~~~~~~~~^^^^^
KeyError: 'country_name'
2023-09-08 07:40:17 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' ps5',
 'position': 3,
 'price': '3.690,00\xa0kr.',
 'product_url': 'https://www.proshop.dk/Spillekonsol/Sony-5-Digital-Edition-Nordic/3033825?utm_source=google&utm_medium=cpc&utm_campaign=searchengine',
 'title': 'Sony 5 - Digital Edition (Nordic)',
 'url': 'proshop.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_name=item['country_name'])
                                                 ~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\scrapy\item.py", line 79, in __getitem__
    return self._values[key]
           ~~~~~~~~~~~~^^^^^
KeyError: 'country_name'
2023-09-08 07:40:17 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' ps5',
 'position': 4,
 'price': '2.999,00\xa0kr.',
 'product_url': 'https://www.telia.dk/shop/playstation/sony-playstation-5-23-bundle-med-abonnement/#/white/0-gb',
 'title': 'Sony PlayStation 5 med abonnement. Min.pris: 5.302,00kr. 6 mdr. '
          'binding',
 'url': 'telia.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_name=item['country_name'])
                                                 ~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\scrapy\item.py", line 79, in __getitem__
    return self._values[key]
           ~~~~~~~~~~~~^^^^^
KeyError: 'country_name'
2023-09-08 07:40:17 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' ps5',
 'position': 5,
 'price': '4.359,00\xa0kr.',
 'product_url': 'https://www.power.dk/gaming-og-underholdning/playstation/playstation-konsoller/playstation-5/p-1840111/',
 'title': 'PLAYSTATION 5',
 'url': 'power.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_name=item['country_name'])
                                                 ~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\scrapy\item.py", line 79, in __getitem__
    return self._values[key]
           ~~~~~~~~~~~~^^^^^
KeyError: 'country_name'
2023-09-08 07:40:17 [scrapy] DEBUG: Retrying <GET https://www.google.com/sorry/index?continue=https://www.google.com/search%3Fq%3D%2Biphone%2B13%26hl%3Den%26gl%3DDK%26start%3D0&hl=en&q=EgRdpA0SGJCT6qcGIjBXI7u1WVTgoFs4V8RlvhS3FUlVLZlKQsxYr-8YrJNl3mVtbnXJlw7m1pj95GgLibIyAXJaAUM> (failed 2 times): 429 Unknown Status
2023-09-08 07:40:17 [scrapy] DEBUG: Crawled (200) <GET https://www.google.com/search?q=iphone+14&hl=en&gl=DK&start=0> (referer: None)
2023-09-08 07:40:17 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': 'iphone 14',
 'position': 1,
 'price': '6.666,00\xa0kr.',
 'product_url': 'https://www.power.dk/mobil-og-foto/mobiltelefoner/apple-iphone-14-128-gb-midnat/p-1803962/',
 'title': 'APPLE IPHONE 14 128 GB MIDNAT',
 'url': 'power.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_name=item['country_name'])
                                                 ~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\scrapy\item.py", line 79, in __getitem__
    return self._values[key]
           ~~~~~~~~~~~~^^^^^
KeyError: 'country_name'
2023-09-08 07:40:17 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': 'iphone 14',
 'position': 2,
 'price': '5.399,00\xa0kr.',
 'product_url': 'https://www.telia.dk/shop/apple/apple-iphone-14/#/midnight/128-gb/1',
 'title': 'Apple iPhone 14 128GB Midnight. Min.pris: 7.202,00kr. 6 mdr. '
          'binding',
 'url': 'telia.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_name=item['country_name'])
                                                 ~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\scrapy\item.py", line 79, in __getitem__
    return self._values[key]
           ~~~~~~~~~~~~^^^^^
KeyError: 'country_name'
2023-09-08 07:40:17 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': 'iphone 14',
 'position': 3,
 'price': '4.799,00\xa0kr.',
 'product_url': 'https://www.telenor.dk/shop/mobil/apple/iphone-13-128gb-green/?cycleCount=none',
 'title': 'Apple iPhone 13 - 128 GB - Grøn med abonnementsaftale. Mindstepris '
          '6613.00 Kr.',
 'url': 'telenor.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_name=item['country_name'])
                                                 ~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\scrapy\item.py", line 79, in __getitem__
    return self._values[key]
           ~~~~~~~~~~~~^^^^^
KeyError: 'country_name'
2023-09-08 07:40:17 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': 'iphone 14',
 'position': 4,
 'price': '5.706,99\xa0kr.',
 'product_url': 'https://www.refurbed.dk/p/iphone-14/?co=dk&utm_cluster=gradeA&utm_content=iphone-14&utm_group=iphone-14',
 'title': 'iPhone 14',
 'url': 'refurbed.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_name=item['country_name'])
                                                 ~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\scrapy\item.py", line 79, in __getitem__
    return self._values[key]
           ~~~~~~~~~~~~^^^^^
KeyError: 'country_name'
2023-09-08 07:40:17 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': 'iphone 14',
 'position': 5,
 'price': '5.761,00\xa0kr.',
 'product_url': 'https://yousee.dk/mobil/mobiltelefoner/apple/iphone-14/1468/mobil_80/kontant/',
 'title': 'Apple iPhone 14 128 GB Midnat med abonnementsaftale. Mindstepris '
          '7.075,00 kr.',
 'url': 'yousee.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_name=item['country_name'])
                                                 ~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\scrapy\item.py", line 79, in __getitem__
    return self._values[key]
           ~~~~~~~~~~~~^^^^^
KeyError: 'country_name'
2023-09-08 07:40:17 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': 'iphone 14',
 'position': 6,
 'price': '7.149,00\xa0kr.',
 'product_url': 'https://www.elgiganten.dk/product/mobil-tablet-smartwatch/mobiltelefon/iphone-14-5g-smartphone-128gb-midnight/522692',
 'title': 'iPhone 14 – 5G smartphone 128GB Midnight',
 'url': 'elgiganten.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_name=item['country_name'])
                                                 ~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\scrapy\item.py", line 79, in __getitem__
    return self._values[key]
           ~~~~~~~~~~~~^^^^^
KeyError: 'country_name'
2023-09-08 07:40:17 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': 'iphone 14',
 'position': 7,
 'price': '4.249,00\xa0kr.',
 'product_url': 'https://greenmind.dk/telefoner/iphones/iphone-12/iphone-12-pro/apple-iphone-12-pro-128-gb-stillehavsbla-brugt-okay-stand-25325',
 'title': 'Apple iPhone 12 Pro 128 GB Stillehavsblå Brugt - Okay stand',
 'url': 'greenmind.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_name=item['country_name'])
                                                 ~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\scrapy\item.py", line 79, in __getitem__
    return self._values[key]
           ~~~~~~~~~~~~^^^^^
KeyError: 'country_name'
2023-09-08 07:40:17 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': 'iphone 14',
 'position': 8,
 'price': '6.777,00\xa0kr.',
 'product_url': 'https://www.proshop.dk/Mobil/Apple-iPhone-14-5G-128GB-Midnight/3104588?utm_source=google&utm_medium=cpc&utm_campaign=searchengine',
 'title': 'Apple iPhone 14 5G 128GB - Midnight',
 'url': 'proshop.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_name=item['country_name'])
                                                 ~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\scrapy\item.py", line 79, in __getitem__
    return self._values[key]
           ~~~~~~~~~~~~^^^^^
KeyError: 'country_name'
2023-09-08 07:40:17 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': 'iphone 14',
 'position': 9,
 'price': '4.799,00\xa0kr.',
 'product_url': 'https://www.telenor.dk/shop/mobil/apple/apple-iphone-13--128gb-midnight/?cycleCount=none',
 'title': 'Apple iPhone 13 - 128 GB - Midnight med abonnementsaftale. '
          'Mindstepris 6613.00 Kr.',
 'url': 'telenor.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_name=item['country_name'])
                                                 ~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\scrapy\item.py", line 79, in __getitem__
    return self._values[key]
           ~~~~~~~~~~~~^^^^^
KeyError: 'country_name'
2023-09-08 07:40:17 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': 'iphone 14',
 'position': 10,
 'price': '5.399,00\xa0kr.',
 'product_url': 'https://www.telia.dk/shop/apple/apple-iphone-14/#/blue/128-gb/1',
 'title': 'Apple iPhone 14 128GB Blue.. Min.pris: 7.202,00kr. 6 mdr. binding',
 'url': 'telia.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_name=item['country_name'])
                                                 ~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\scrapy\item.py", line 79, in __getitem__
    return self._values[key]
           ~~~~~~~~~~~~^^^^^
KeyError: 'country_name'
2023-09-08 07:40:17 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': 'iphone 14',
 'position': 11,
 'price': '6.839,99\xa0kr.',
 'product_url': 'https://www.refurbed.dk/p/iphone-14-pro/?co=dk&utm_cluster=gradeB&utm_content=iphone-14-pro&utm_group=iphone-14-pro',
 'title': '>> iPhone 14 Pro <<',
 'url': 'refurbed.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_name=item['country_name'])
                                                 ~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\scrapy\item.py", line 79, in __getitem__
    return self._values[key]
           ~~~~~~~~~~~~^^^^^
KeyError: 'country_name'
2023-09-08 07:40:17 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': 'iphone 14',
 'position': 12,
 'price': '5.579,00\xa0kr.',
 'product_url': 'https://swappie.com/dk/iphone/iphone-14/iphone-14-128gb-bla-18/',
 'title': 'iPhone 14 128GB Blå Apple',
 'url': 'swappie.com',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_name=item['country_name'])
                                                 ~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\scrapy\item.py", line 79, in __getitem__
    return self._values[key]
           ~~~~~~~~~~~~^^^^^
KeyError: 'country_name'
2023-09-08 07:40:17 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': 'iphone 14',
 'position': 13,
 'price': '6.666,00\xa0kr.',
 'product_url': 'https://www.power.dk/mobil-og-foto/mobiltelefoner/apple-iphone-14-128-gb-stjerneskaer/p-1803963/',
 'title': 'APPLE IPHONE 14 128 GB STJERNESKÆR',
 'url': 'power.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_name=item['country_name'])
                                                 ~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\scrapy\item.py", line 79, in __getitem__
    return self._values[key]
           ~~~~~~~~~~~~^^^^^
KeyError: 'country_name'
2023-09-08 07:40:17 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': 'iphone 14',
 'position': 14,
 'price': '5.496,00\xa0kr.',
 'product_url': 'https://www.telmore.dk/shop/mobiltelefoner/Apple/iphone-14?cid=_semt_terminal_terminal_Shopping_Shopping_u0617',
 'title': 'Apple iPhone 14 128 GB - Product Red. Mindstepris 7.290,00 kr.',
 'url': 'telmore.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_name=item['country_name'])
                                                 ~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\scrapy\item.py", line 79, in __getitem__
    return self._values[key]
           ~~~~~~~~~~~~^^^^^
KeyError: 'country_name'
2023-09-08 07:40:17 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': 'iphone 14',
 'position': 15,
 'price': '8.599,00\xa0kr.',
 'product_url': 'https://www.foetex.dk/produkter/iphone-14-pro-128gb-space-black/200162701/',
 'title': '"IPHONE 14 PRO 128GB SPACE BLACK"',
 'url': 'foetex.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_name=item['country_name'])
                                                 ~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\scrapy\item.py", line 79, in __getitem__
    return self._values[key]
           ~~~~~~~~~~~~^^^^^
KeyError: 'country_name'
2023-09-08 07:40:17 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': 'iphone 14',
 'position': 16,
 'price': '14.683,00\xa0kr.',
 'product_url': 'https://www.boligcenter.dk/elektronik/telefoner-tablets/mobiltelefoner/smartphone-apple-iphone-14-pro-805626',
 'title': 'Smartphone Apple iPhone 14 Pro',
 'url': 'boligcenter.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_name=item['country_name'])
                                                 ~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\scrapy\item.py", line 79, in __getitem__
    return self._values[key]
           ~~~~~~~~~~~~^^^^^
KeyError: 'country_name'
2023-09-08 07:40:17 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': 'iphone 14',
 'position': 17,
 'price': '6.777,00\xa0kr.',
 'product_url': 'https://www.proshop.dk/Mobil/Apple-iPhone-14-5G-128GB-Starlight/3104589?utm_source=google&utm_medium=cpc&utm_campaign=searchengine',
 'title': 'Apple iPhone 14 5G 128GB - Starlight',
 'url': 'proshop.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_name=item['country_name'])
                                                 ~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\scrapy\item.py", line 79, in __getitem__
    return self._values[key]
           ~~~~~~~~~~~~^^^^^
KeyError: 'country_name'
2023-09-08 07:40:17 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': 'iphone 14',
 'position': 18,
 'price': '8.499,00\xa0kr.',
 'product_url': 'https://www.power.dk/mobil-og-foto/mobiltelefoner/apple-iphone-14-pro-128-gb-space-black/p-1803992/',
 'title': 'APPLE IPHONE 14 PRO 128 GB SPACE BLACK',
 'url': 'power.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_name=item['country_name'])
                                                 ~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\scrapy\item.py", line 79, in __getitem__
    return self._values[key]
           ~~~~~~~~~~~~^^^^^
KeyError: 'country_name'
2023-09-08 07:40:17 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': 'iphone 14',
 'position': 19,
 'price': '4.895,00\xa0kr.',
 'product_url': 'https://www.phonetrade.dk/kob/iphone-14/stjerneskaer-128gb-brugbar-829',
 'title': 'iPhone 14, 128GB, Stjerneskær',
 'url': 'phonetrade.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_name=item['country_name'])
                                                 ~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\scrapy\item.py", line 79, in __getitem__
    return self._values[key]
           ~~~~~~~~~~~~^^^^^
KeyError: 'country_name'
2023-09-08 07:40:17 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': 'iphone 14',
 'position': 20,
 'price': '5.496,00\xa0kr.',
 'product_url': 'https://www.telmore.dk/shop/mobiltelefoner/Apple/iphone-14?cid=_semt_terminal_terminal_Shopping_Shopping_u0617',
 'title': 'Apple iPhone 14 128 GB - Purple. Mindstepris 7.290,00 kr.',
 'url': 'telmore.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_name=item['country_name'])
                                                 ~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\scrapy\item.py", line 79, in __getitem__
    return self._values[key]
           ~~~~~~~~~~~~^^^^^
KeyError: 'country_name'
2023-09-08 07:40:17 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': 'iphone 14',
 'position': 21,
 'price': '6.291,00\xa0kr.',
 'product_url': 'https://www.elgiganten.dk/product/outlet/iphone-14-5g-smartphone-128gb-product-red/653032',
 'title': 'iPhone 14 – 5G smartphone 128GB Product Red',
 'url': 'elgiganten.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_name=item['country_name'])
                                                 ~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\scrapy\item.py", line 79, in __getitem__
    return self._values[key]
           ~~~~~~~~~~~~^^^^^
KeyError: 'country_name'
2023-09-08 07:40:17 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': 'iphone 14',
 'position': 22,
 'price': '5.399,00\xa0kr.',
 'product_url': 'https://www.telia.dk/shop/apple/apple-iphone-14/#/starlight/128-gb/1',
 'title': 'Apple iPhone 14 128GB Starlight. Min.pris: 7.202,00kr. 6 mdr. '
          'binding',
 'url': 'telia.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_name=item['country_name'])
                                                 ~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\scrapy\item.py", line 79, in __getitem__
    return self._values[key]
           ~~~~~~~~~~~~^^^^^
KeyError: 'country_name'
2023-09-08 07:40:17 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': 'iphone 14',
 'position': 23,
 'price': '5.761,00\xa0kr.',
 'product_url': 'https://yousee.dk/mobil/mobiltelefoner/apple/iphone-14/1611/mobil_80/kontant/',
 'title': 'Apple iPhone 14 128 GB Gul med abonnementsaftale. Mindstepris '
          '7.075,00 kr.',
 'url': 'yousee.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_name=item['country_name'])
                                                 ~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\scrapy\item.py", line 79, in __getitem__
    return self._values[key]
           ~~~~~~~~~~~~^^^^^
KeyError: 'country_name'
2023-09-08 07:40:17 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': 'iphone 14',
 'position': 24,
 'price': '5.496,00\xa0kr.',
 'product_url': 'https://www.telmore.dk/shop/mobiltelefoner/Apple/iphone-14?cid=_semt_terminal_terminal_Shopping_Shopping_u0617',
 'title': 'Apple iPhone 14 128 GB - Sky Blue. Mindstepris 7.290,00 kr.',
 'url': 'telmore.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_name=item['country_name'])
                                                 ~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\scrapy\item.py", line 79, in __getitem__
    return self._values[key]
           ~~~~~~~~~~~~^^^^^
KeyError: 'country_name'
2023-09-08 07:40:17 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': 'iphone 14',
 'position': 25,
 'price': '5.761,00\xa0kr.',
 'product_url': 'https://yousee.dk/mobil/mobiltelefoner/apple/iphone-14/1471/mobil_80/kontant/',
 'title': 'Apple iPhone 14 128 GB Stjerneskær med abonnementsaftale. '
          'Mindstepris 7.075,00 kr.',
 'url': 'yousee.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_name=item['country_name'])
                                                 ~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\scrapy\item.py", line 79, in __getitem__
    return self._values[key]
           ~~~~~~~~~~~~^^^^^
KeyError: 'country_name'
2023-09-08 07:40:17 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': 'iphone 14',
 'position': 26,
 'price': '5.399,00\xa0kr.',
 'product_url': 'https://www.telia.dk/shop/apple/apple-iphone-14/#/purple/128-gb/1',
 'title': 'Apple iPhone 14 128GB Purple. Min.pris: 7.202,00kr. 6 mdr. binding',
 'url': 'telia.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_name=item['country_name'])
                                                 ~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\scrapy\item.py", line 79, in __getitem__
    return self._values[key]
           ~~~~~~~~~~~~^^^^^
KeyError: 'country_name'
2023-09-08 07:40:17 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': 'iphone 14',
 'position': 27,
 'price': '5.666,00\xa0kr.',
 'product_url': 'https://www.elgiganten.dk/product/mobil-tablet-smartwatch/mobiltelefon/iphone-13-5g-smartphone-128gb-midnight/361879',
 'title': 'iPhone 13 – 5G smartphone 128GB Midnight',
 'url': 'elgiganten.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_name=item['country_name'])
                                                 ~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\scrapy\item.py", line 79, in __getitem__
    return self._values[key]
           ~~~~~~~~~~~~^^^^^
KeyError: 'country_name'
2023-09-08 07:40:17 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': 'iphone 14',
 'position': 28,
 'price': '2.989,99\xa0kr.',
 'product_url': 'https://www.refurbed.dk/p/iphone-12/?co=dk&utm_cluster=gradeA&utm_content=iphone-12&utm_group=iphone-12',
 'title': 'iPhone 12',
 'url': 'refurbed.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_name=item['country_name'])
                                                 ~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\scrapy\item.py", line 79, in __getitem__
    return self._values[key]
           ~~~~~~~~~~~~^^^^^
KeyError: 'country_name'
2023-09-08 07:40:17 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': 'iphone 14',
 'position': 29,
 'price': '5.896,99\xa0kr.',
 'product_url': 'https://www.refurbed.dk/p/iphone-14-plus/?co=dk&utm_cluster=gradeC&utm_content=iphone-14-plus&utm_group=iphone-14-plus',
 'title': '>> iPhone 14 Plus <<',
 'url': 'refurbed.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_name=item['country_name'])
                                                 ~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\scrapy\item.py", line 79, in __getitem__
    return self._values[key]
           ~~~~~~~~~~~~^^^^^
KeyError: 'country_name'
2023-09-08 07:40:17 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': 'iphone 14',
 'position': 30,
 'price': None,
 'product_url': None,
 'title': None,
 'url': '',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 33, in process_item
    location = Location.objects.get(country_name=item['country_name'])
                                                 ~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\scrapy\item.py", line 79, in __getitem__
    return self._values[key]
           ~~~~~~~~~~~~^^^^^
KeyError: 'country_name'
2023-09-08 07:40:18 [scrapy] ERROR: Gave up retrying <GET https://www.google.com/sorry/index?continue=https://www.google.com/search%3Fq%3D%2Biphone%2B13%26hl%3Den%26gl%3DDK%26start%3D0&hl=en&q=EgRdpA0SGJCT6qcGIjBXI7u1WVTgoFs4V8RlvhS3FUlVLZlKQsxYr-8YrJNl3mVtbnXJlw7m1pj95GgLibIyAXJaAUM> (failed 3 times): 429 Unknown Status
2023-09-08 07:40:18 [scrapy] DEBUG: Crawled (429) <GET https://www.google.com/sorry/index?continue=https://www.google.com/search%3Fq%3D%2Biphone%2B13%26hl%3Den%26gl%3DDK%26start%3D0&hl=en&q=EgRdpA0SGJCT6qcGIjBXI7u1WVTgoFs4V8RlvhS3FUlVLZlKQsxYr-8YrJNl3mVtbnXJlw7m1pj95GgLibIyAXJaAUM> (referer: None)
2023-09-08 07:40:18 [scrapy] INFO: Ignoring response <429 https://www.google.com/sorry/index?continue=https://www.google.com/search%3Fq%3D%2Biphone%2B13%26hl%3Den%26gl%3DDK%26start%3D0&hl=en&q=EgRdpA0SGJCT6qcGIjBXI7u1WVTgoFs4V8RlvhS3FUlVLZlKQsxYr-8YrJNl3mVtbnXJlw7m1pj95GgLibIyAXJaAUM>: HTTP status code is not handled or not allowed
2023-09-08 07:40:18 [scrapy] INFO: Closing spider (finished)
2023-09-08 07:40:18 [scrapy] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 4723,
 'downloader/request_count': 8,
 'downloader/request_method_count/GET': 8,
 'downloader/response_bytes': 896797,
 'downloader/response_count': 8,
 'downloader/response_status_count/200': 4,
 'downloader/response_status_count/302': 1,
 'downloader/response_status_count/429': 3,
 'elapsed_time_seconds': 4.645824,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2023, 9, 8, 2, 40, 18, 181352),
 'httpcompression/response_bytes': 3226632,
 'httpcompression/response_count': 4,
 'httperror/response_ignored_count': 1,
 'httperror/response_ignored_status_count/429': 1,
 'log_count/DEBUG': 8,
 'log_count/ERROR': 45,
 'log_count/INFO': 9,
 'response_received_count': 5,
 'retry/count': 2,
 'retry/max_reached': 1,
 'retry/reason_count/429 Unknown Status': 2,
 'scheduler/dequeued': 8,
 'scheduler/dequeued/memory': 8,
 'scheduler/enqueued': 8,
 'scheduler/enqueued/memory': 8,
 'start_time': datetime.datetime(2023, 9, 8, 2, 40, 13, 535528)}
2023-09-08 07:40:18 [scrapy] INFO: Spider closed (finished)
